# /cre-node/project.yaml — V4 format (matches --target tenderly-fork)
tenderly-fork:
  rpcs:
    - chain-name: "ethereum-mainnet-base-1"
      url: "https://virtual.base.eu.rpc.tenderly.co/2598f75a-1c3a-4772-8c10-43d29099b8d1"
